<?php

$default_values = array(
  // HEADER-SECTION //
  'navbar-button-title' => 'Зв\'язатись з нами',
  'navbar-button-url' => '/#feedback',
  'navbar-button-color' => 'btn-blue',
  'navbar-button-icon' => '',
  // FOOTER-SECTION //
  'footer-social-icon-color' => 'duotone-icon-blue',
  // HOME-PAGE-HEADER-SECTION //
  'home-page-header-title' => 'Розкрийте (потенціал) # вашої * дитини',
  'home-page-header-subtitle' => 'Ми віримо, що кожна дитина має унікальні таланти # та здібності, які чекають на відкриття',
  'home-page-header-icon' => 'ph-heart',
  'home-page-header-icon-color' => 'icon-rose',
  'home-page-header-first-button-text' => 'Зв\'язатись з нами',
  'home-page-header-first-button-url' => '/#feedback',
  'home-page-header-first-button-color' => 'btn-blue',
  'home-page-header-first-button-icon' => '',
  'home-page-header-second-button-enabled' => '1',
  'home-page-header-second-button-text' => 'Як ми працюємо',
  'home-page-header-second-button-url' => '/#gallery',
  'home-page-header-second-button-color' => 'btn-outline-amber',
  'home-page-header-second-button-icon' => 'ph-images',
  // HOME-PAGE-ABOUT-SECTION //
  'home-page-about-first-card-title' => 'Кожен з дітей знаходить своє покликання та розвиває таланти у нашій школі',
  'home-page-about-first-card-subtitle' => 'Ми навчаємо дітей виразно висловлювати свої думки, малювати мрії, творити музику та вивчати англійську мову',
  'home-page-about-first-card-tags' => 'Англійська з носієм; Логопед; Preschool; Малювання; Фортепіано; Гітара; Акторська майстерність',
  'home-page-about-first-card-icon' => 'ph-sparkle',
  'home-page-about-first-card-color' => 'card-sky',
  'home-page-about-second-card-title' => 'Ми маємо видатних вчителів, готових подарувати вашій дитині найкраще навчання та підтримку',
  'home-page-about-second-card-subtitle' => '',
  'home-page-about-second-card-icon' => 'ph-graduation-cap',
  'home-page-about-second-card-color' => 'card-yellow',
  // HOME-PAGE-ADVANTAGES-SECTION //
  'home-page-advantages-title' => 'Чому обирають нас?',
  'home-page-advantages-subtitle' => 'Наші учні обирають навчання в нашій дитячій школі через високу якість освіти',
  'home-page-advantages-first-card-enabled' => '1',
  'home-page-advantages-first-card-title' => 'Повний Розвиток',
  'home-page-advantages-first-card-subtitle' => 'Ми вважаємо, що навчання має сприяти повному розвитку кожної дитини',
  'home-page-advantages-first-card-icon' => 'ph-grains',
  'home-page-advantages-first-card-icon-color' => 'duotone-icon-amber',
  'home-page-advantages-second-card-enabled' => '1',
  'home-page-advantages-second-card-title' => 'Особистий Підхід',
  'home-page-advantages-second-card-subtitle' => 'Ми розуміємо, що кожна дитина унікальна та має власні потреби та таланти',
  'home-page-advantages-second-card-icon' => 'ph-baby',
  'home-page-advantages-second-card-icon-color' => 'duotone-icon-blue',
  'home-page-advantages-third-card-enabled' => '1',
  'home-page-advantages-third-card-title' => 'Любов до Дітей',
  'home-page-advantages-third-card-subtitle' => 'Наші вчителі та персонал завжди готові дарувати дітям увагу та тепло',
  'home-page-advantages-third-card-icon' => 'ph-heart',
  'home-page-advantages-third-card-icon-color' => 'duotone-icon-rose',
  'home-page-advantages-fourth-card-enabled' => '',
  'home-page-advantages-fourth-card-title' => 'Інноваційні Методики',
  'home-page-advantages-fourth-card-subtitle' => 'Ми використовуємо сучасні та передові методики навчання, щоб зацікавити дітей і розвивати їхні навички',
  'home-page-advantages-fourth-card-icon' => 'ph-compass',
  'home-page-advantages-fourth-card-icon-color' => 'duotone-icon-violet',
  // HOME-PAGE-CLASSES-SECTION //
  'home-page-classes-title' => 'Розкриваємо * таланти',
  'home-page-classes-subtitle' => 'Навчання, творчість, (розвиток) в нашій школі',
  'home-page-classes-icon' => 'ph-shooting-star',
  'home-page-classes-icon-color' => 'duotone-icon-blue',
  'home-page-classes-card-color' => 'card-blue',
  'home-page-classes-first-button-text' => 'Зв\'язатись з нами',
  'home-page-classes-first-button-url' => '/#feedback',
  'home-page-classes-first-button-color' => 'btn-blue',
  'home-page-classes-first-button-icon' => '',
  'home-page-classes-second-button-enabled' => '1',
  'home-page-classes-second-button-text' => 'Дивитись прейскурант',
  'home-page-classes-second-button-url' => '/pricing',
  'home-page-classes-second-button-color' => 'btn-outline-blue',
  'home-page-classes-second-button-icon' => '',
  // HOME-PAGE-GALLERY-SECTION //
  'home-page-gallery-title' => 'Як ми * # працюємо',
  'home-page-gallery-subtitle' => 'Наша робота заснована на вірі в унікальність кожної дитини. Ми створюємо стимулююче середовище, де кожен має можливість розвинути свої таланти та здібності. Наші методи надихають та сприяють повноцінному розвитку кожної дитини.',
  'home-page-gallery-icon' => 'ph-lightbulb-filament',
  'home-page-gallery-icon-color' => 'duotone-icon-green',
  'home-page-gallery-player-color' => 'duotone-icon-blue',
  'home-page-gallery-first-button-text' => 'Наша галерея',
  'home-page-gallery-first-button-url' => '/gallery',
  'home-page-gallery-first-button-color' => 'btn-blue',
  'home-page-gallery-first-button-icon' => 'ph-panorama',
  'home-page-gallery-second-button-enabled' => '',
  'home-page-gallery-second-button-text' => 'Зв\'язатись з нами',
  'home-page-gallery-second-button-url' => '/#feedback',
  'home-page-gallery-second-button-color' => 'btn-outline-blue',
  'home-page-gallery-second-button-icon' => '',
  // HOME-PAGE--SECTION //
  'home-page-pricing-title' => 'Рекомендовані напрямки навчання',
  'home-page-pricing-subtitle' => 'У цьому розділі ми представляємо найрекомендованіші послуги, які допоможуть вашій дитині розвинутися і навчитися новому. Для докладнішої інформації та повного переліку послуг, будь ласка, перейдіть на сторінку «Прейскурант»',
  'home-page-pricing-icon' => 'ph-book-bookmark',
  'home-page-pricing-icon-color' => 'duotone-icon-violet',
  'home-page-pricing-first-button-text' => 'Повний прейскурант',
  'home-page-pricing-first-button-url' => '/pricing',
  'home-page-pricing-first-button-color' => 'btn-violet',
  'home-page-pricing-first-button-icon' => 'ph-bookmarks',
  'home-page-pricing-second-button-enabled' => '',
  'home-page-pricing-second-button-text' => 'Зв\'язатись з нами',
  'home-page-pricing-second-button-url' => '/#feedback',
  'home-page-pricing-second-button-color' => 'btn-outline-blue',
  'home-page-pricing-second-button-icon' => '',
  // HOME-PAGE-FEEDBACK-SECTION //
  'home-page-feedback-title' => 'Зв\'язок * з нами',
  'home-page-feedback-subtitle' => 'Залишіть нам повідомлення та ми обов\'язково зв\'яжемось з вами за першої можливості',
  'home-page-feedback-icon' => 'ph-chats-circle',
  'home-page-feedback-icon-color' => 'duotone-icon-green',
  'home-page-feedback-card-color' => 'card-blue',
  // PRICING-PAGE-HEADER-SECTION //
  'pricing-page-header-title' => 'Ціновий атлас вартості # навчання в нашій дитячій школі',
  'pricing-page-header-subtitle' => 'Ознайомтесь з офіційним прейскурантом навчання в нашій школі. # Інвестиція у знання - цінний подарунок вашій дитині!',
  'pricing-page-header-label-text' => 'Прейскурант',
  'pricing-page-header-label-icon' => 'ph-lightning',
  'pricing-page-header-label-color' => 'duotone-icon-blue',
  // PRICING-PAGE-CLASSES-SECTION //
  'pricing-page-classes-tabs-color' => 'tabs-blue',
  'pricing-page-classes-cards-color' => 'card-blue',
  // PRICING-PAGE-FEEDBACK-SECTION //
  'pricing-page-feedback-title' => 'Записатись до нас',
  'pricing-page-feedback-subtitle' => 'Залишіть нам повідомлення та ми обов\'язково зв\'яжемось з вами за першої можливості',
  'pricing-page-feedback-icon' => 'ph-chats',
  'pricing-page-feedback-icon-color' => 'duotone-icon-green',
  'pricing-page-feedback-card-color' => 'card-blue',
  // GALLERY-PAGE-HEADER-SECTION //
  'gallery-page-header-title' => 'Галерея творчих досягнень наших учнів',
  'gallery-page-header-subtitle' => 'Пориньте у світ яскравих фарб та неповторних ідей, створених талановитими руками наших учнів. # Кожна робота - це крок на шляху до великого мистецтва!',
  'gallery-page-header-label-text' => 'Галерея',
  'gallery-page-header-label-icon' => 'ph-slideshow',
  'gallery-page-header-label-color' => 'duotone-icon-rose',
  // GALLERY-PAGE-MEDIA-SECTION //
  'gallery-page-media-is-tabs-enabled' => '1',
  'gallery-page-media-is-empty-enabled' => '',
  'gallery-page-media-count' => 32,
  'gallery-page-media-tabs-color' => 'tabs-rose',
  'gallery-page-media-pagination-color' => 'pagination-rose',
  'gallery-page-media-video-color' => 'duotone-icon-rose',
  // SERVICES-TELEGRAM-SECTION //
  'services-telegram-token' => '',
  'services-telegram-group' => '',
  // SERVICES-GOOGLE-SECTION //
  'services-google-map' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d162757.83675632364!2d30.367885485142043!3d50.40213793556894!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cf4ee15a4505%3A0x764931d2170146fe!2z0JrQuNC10LIsIDAyMDAw!5e0!3m2!1sru!2sua!4v1718004923369!5m2!1sru!2sua" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  // SERVICES-CLOUDFLARE-SECTION //
  'services-cloudflare-turnstile-secret' => '',
  'services-cloudflare-turnstile-sitekey' => '',
  // CONTACTS-DIRECT-SECTION //
  'contacts-direct-email' => 'staccato@gmail.com',
  'contacts-direct-phone' => '+380 (96) 123 45 67',
  'contacts-direct-address' => 'м. Київ, вул. Велика Васильківська, 00',
  // CONTACTS-SOCIAL-SECTION //
  'contacts-social-instagram' => 'https://instagram.com/',
  'contacts-social-facebook' => 'https://facebook.com/',
  'contacts-social-telegram' => 'https://t.me/',
  'contacts-social-whatsapp' => '',
  'contacts-social-x' => '',
  'contacts-social-youtube' => 'https://youtube.com/',
  'contacts-social-tiktok' => 'https://tiktok.com/',
  'contacts-social-linkedin' => '',
  'contacts-social-linktree' => '',
  'contacts-social-mastodon' => '',
  'contacts-social-messenger' => '',
  'contacts-social-threads' => '',
  'contacts-social-snapchat' => '',
  'contacts-social-tumblr' => '',
  'contacts-social-pinterest' => '',
);

?>